0 to 1: 提升超过0.1dB
RBSR : 85/882
DBSR ：53/882
ormSR ：73/882
三个网络下都有提升的比例：3/882，step 613，756，818
31/882，step：2,25,33,45,47,88,166,183,240,262,269,285,367,368,377,399,462,549,575,613,690,732,755,756,761,774,775,807,813,818,878

1 to 2: 提升超过0.1dB
RBSR ：57/882
DBSR : 51/882
ormSR ：42/882
三个网络下都有提升的比例：0
11/882
step：141,240,245,258,366,572,573,581,586,730,755

2 to 3: 提升超过0.1dB
RBSR ：45/882
BSR : 44/882
ormSR ：41/882
三个网络下都有提升的比例：3/882，step89，268，576
17/882
step：61,87,89,92,246,249,268,443,576,584,585,648,661,673,678,743,761

3 to 4: 提升超过0.1dB
RBSR ：54/882
DBSR : 38/882
ormSR ：35/882
三个网络下都有提升的比例：0/882，step
13/882
step：33,42,53,60,241,248,265,371,576,738,740,760,800


4 to 5: 提升超过0.1dB
RBSR ：53/882
DBSR : 47/882
ormSR ：32/882
三个网络下都有提升的比例：2/882，step610，755
17/882
step：54,99,154,241,252,267,399,464,575,585,610,667,730,731,755,876,877

5 to6 : 提升超过0.1dB
RBSR ：33/882
DBSR : 43/882
ormSR ：40/882
三个网络下都有提升的比例：1/882，step576
14/882
step：40,42,248,267,348,360,464,576,584,609,645,735,737,807

6 to 7 : 提升超过0.1dB
RBSR ：31/882
DBSR : 47/882
ormSR ：35/882
三个网络下都有提升的比例：0/882，step
10/882
step：43,241,249,585,612,740,756,758,806,871

7 to 8 : 提升超过0.1dB
RBSR ：33/882
DBSR : 37/882
ormSR ：34/882
三个网络下都有提升的比例：1/882，step87
8/882
step：84,87,365,574,576,657,707,875

8 to 9 : 提升超过0.1dB
RBSR ：37/882
DBSR :  42/882
ormSR ：40/882
三个网络下都有提升的比例：2/882，step248, 612
13/882
step：42,46,51,239,248,348,366,612,656,657,664,674,750

9 to 10 : 提升超过0.1dB
RBSR ：36 /882
DBSR : 32/882
ormSR ：34/882
三个网络下都有提升的比例：1/882，step
11/882
step：89,247,249,255,381,464,585,612,667,730,738

10 to 11 : 提升超过0.1dB
RBSR ：27/882
DBSR : 43/882
ormSR ：39/882
三个网络下都有提升的比例：1/882，step759
13/882
step：46,81,87,90,94,239,249,574,584,732,755,759,767


11 to 12 : 提升超过0.1dB
RBSR ：30/882
DBSR : 44/882
ormSR ：45/882
三个网络下都有提升的比例：2/882，step240, 610
13/882
step：240,258,285,306,348,465,571,582,609,610,641,667,812

12 to 13 : 提升超过0.1dB
RBSR ：24/882
DBSR : 37/882
ormSR ：31/882
三个网络下都有提升的比例：2/882，step 248, 756
13/882
step：45,48,245,248,572,577,610,678,737,743,756,764,767


Traceback (most recent call last):
  File "/mnt/diskb/penglong/dx/code/SR/zff_track2_fenxi.py", line 157, in <module>
    BurstSR_Test_Network(args).test()
  File "/mnt/diskb/penglong/dx/code/SR/zff_track2_fenxi.py", line 122, in test
    PSNR_temp = self.aligned_psnr_fn(burst_rgb, labels, burst).cpu().numpy()
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/dx/code/SR/utils/metrics.py", line 332, in forward
    psnr_all = [self.psnr(p.unsqueeze(0), g.unsqueeze(0), bi.unsqueeze(0)) for p, g, bi in zip(pred, gt, burst_input)]
  File "/mnt/diskb/penglong/dx/code/SR/utils/metrics.py", line 332, in <listcomp>
    psnr_all = [self.psnr(p.unsqueeze(0), g.unsqueeze(0), bi.unsqueeze(0)) for p, g, bi in zip(pred, gt, burst_input)]
  File "/mnt/diskb/penglong/dx/code/SR/utils/metrics.py", line 324, in psnr
    mse = self.l2(pred, gt, burst_input) + 1e-12
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/dx/code/SR/utils/metrics.py", line 218, in forward
    flow = self.alignment_net(pred / (pred.max() + 1e-6), gt / (gt.max() + 1e-6))
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/dx/code/SR/pwcnet/pwcnet.py", line 278, in forward
    flow = self.net(target_img_re, source_img_re)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/dx/code/SR/pwcnet/pwcnet.py", line 226, in forward
    tenSecond = self.netExtractor(tenSecond)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/dx/code/SR/pwcnet/pwcnet.py", line 107, in forward
    tenOne = self.netOne(tenInput)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor


model.load_state_dict(checkpoint["state_dict"])
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Burstormer:
        size mismatch for conv1.0.weight: copying a param with shape torch.Size([48, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 4, 3, 3]).
        size mismatch for up3.0.weight: copying a param with shape torch.Size([48, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([192, 48, 1, 1]).


Traceback (most recent call last):
  File "/mnt/diskb/penglong/dx/code/SR/zff_track2_eva.py", line 14, in <module>
    from Network_Real_burstSR import Base_Model
  File "/mnt/diskb/penglong/dx/code/SR/Network_Real_burstSR.py", line 9, in <module>
    import pytorch_lightning as pl
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/trainer/__init__.py", line 16, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 30, in <module>
    from pytorch_lightning.accelerators import Accelerator, IPUAccelerator
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/accelerators/__init__.py", line 13, in <module>
    from pytorch_lightning.accelerators.accelerator import Accelerator  # noqa: F401
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 26, in <module>
    from pytorch_lightning.plugins.precision import ApexMixedPrecisionPlugin, NativeMixedPrecisionPlugin, PrecisionPlugin
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/plugins/__init__.py", line 8, in <module>
    from pytorch_lightning.plugins.plugins_registry import (  # noqa: F401
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/plugins/plugins_registry.py", line 20, in <module>
    from pytorch_lightning.plugins.training_type.training_type_plugin import TrainingTypePlugin
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/__init__.py", line 13, in <module>
    from pytorch_lightning.plugins.training_type.tpu_spawn import TPUSpawnPlugin  # noqa: F401
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 27, in <module>
    from pytorch_lightning.loggers import LoggerCollection, TensorBoardLogger
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates



Exception in thread Thread-4:                                                                                                                                      
Traceback (most recent call last):
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/summary/writer/event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/mnt/diskb/penglong/anaconda3/envs/dx9826/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 166, in _write
    f.write(compatify(file_content))
OSError: [Errno 28] No space left on device







  File "/mnt/diskb/penglong/dx/code/SR/utils/metrics.py", line 151, in make_patches
    output1 = output.unfold(2,patch_size*8,stride*8).unfold(3,patch_size*8,stride*8).contiguous()
RuntimeError: maximum size for tensor at dimension 2 is 80 but size is 384


